"""add_interview_sessions

Revision ID: 7477461846f2
Revises: 0001
Create Date: 2026-05-22 16:57:23.485226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '7477461846f2'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interview_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mode', sa.String(), nullable=True),
    sa.Column('jd_text', sa.Text(), nullable=True),
    sa.Column('concept', sa.String(), nullable=True),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('conversation', sa.JSON(), nullable=True),
    sa.Column('debrief', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('question_count', sa.Integer(), nullable=True),
    sa.Column('total_questions', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interview_sessions_id'), 'interview_sessions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_interview_sessions_id'), table_name='interview_sessions')
    op.drop_table('interview_sessions')
    # ### end Alembic commands ###
